package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;

import java.util.ArrayList;
import java.util.List;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.nonAfficheUsers;

import  com.openclassrooms.magicgithub.repository.UserRepository.*;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();
    private List<User> usersNonAffiche = nonAfficheUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: fait ok
        List<User> liste = new ArrayList<User>();
        liste = users;
        return liste;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: A modifier ==> ok
        //
        User personne = User.random();
        List<User> liste = new ArrayList<User>();
        liste = users;
        liste.add(personne);
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: ok
        List<User> liste = new ArrayList<User>();
        liste = users;
        liste.remove( user);
    }
}
